[workspace]
members = [
    "cert",
    "crypto_utils",
    "nebula",
    "cidr_radix",
    "allow_list",
    "header",
    "noise",
    "connection_state",
    "test_utils",
    "tunnel",
    "config",
    "cli"
]